redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\music\\.hermes\\curso-poesia-grega-arcaacia\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "24"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/curso/*"
to = "/:splat"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]